[[commands]]
title = "Toggle Maximize"
name = "maximize"
description = "Makes the window take up the entire screen while retaining the menu bar"
command = "window --toggle zoom-fullscreen"

[[commands]]
title = "Toggle Fullscreen"
name = "fullscreen"
description = "Makes the window take up the entire screen"
command = "window --toggle native-fullscreen"

[[commands]]
title = "DIRECTION"
name = "move-window-DIRECTION"
description = "Move window to the DIRECTION"
command = "window --warp DIRECTION"
directions = ["north", "east", "south", "west"]

[[commands]]
title = "Focus DIRECTION"
name = "focus-window-DIRECTION"
description = "Focus window to the DIRECTION"
command = "window --focus DIRECTION"
directions = ["north", "east", "south", "west"]

[[commands]]
title = "Shuttle DIRECTION"
name = "move-window-to-DIRECTION-space"
description = "Moves currently selected window to the next or previous space."
command = "window --space DIRECTION"
directions = ["next", "prev"]

[[commands]]
title = "Back"
name = "back"
description = "Focuses most recently selected window"
command = "window --focus recent"

[[commands]]
title = "Stack DIRECTION"
name = "stack-DIRECTION"
description = "Stacks one window on another, like we're not using a tiling window manager"
command = "window --stack DIRECTION"
directions = ["north", "east", "south", "west"]

[[commands]]
title = "Swap DIRECTION"
name = "swap-DIRECTION"
description = "Swaps one window with another"
command = "window --swap DIRECTION"
directions = ["north", "east", "south", "west"]

[[commands]]
title = "DIRECTION Space"
name = "focus-space-DIRECTION"
description = "Focus space to the DIRECTION"
command = "space --focus DIRECTION"
directions = ["next", "prev"]

[[commands]]
title = "Create Space"
name = "create-space"
description = "Creates a new space at the end of existing spaces"
command = "space --create"

[[commands]]
title = "Delete Space"
name = "delete-space"
description = "Delects currently selected space"
command = "space --destroy"

[[commands]]
title = "Reset"
name = "binary-space-partition"
description = "Resets all windows of a space to be nice and square"
command = "space --layout bsp"

[[commands]]
title = "Balance DIRECTION"
name = "balance-DIRECTION"
description = "Balance windows in a direction. Less destructive than setting the layout to binary space partition."
command = "space --balance DIRECTION"
directions = ["x-axis", "y-axis"]